#### 1. Import NumPy

Make sure to follow the conventions!

In [ ]:
import numpy as np

#### 2. Create an array of 10 zeros

In [ ]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Expected output

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [ ]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Expected output

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [ ]:
fives_array = np.full(10 , 5)
fives_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# Expected output

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create a vector, named `arr`, of 10 zeros the fifth value of which is 1.

In [ ]:
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# Expected output

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create an array of the integers from 10 to 50

In [ ]:
array = np.arange(10,51)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Expected output

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 7. Reverse an array in **TWO** ways: using 'the Python way' and using a NumPy function

In [ ]:
arr = np.array([1, 2, 3])
arr1 = arr[::-1]
print(f'Using the Python way: {arr1}')
arr2 = np.flip(arr)
print(f'Using a NumPy function: {arr2}')

Using the Python way: [3 2 1]
Using a NumPy function: [3 2 1]


In [ ]:
# Expected output

Using the Python way: [3 2 1]
Using a NumPy function: [3 2 1]


#### 8. Create a 5x5 array with 1 on the border and 0 inside

In [ ]:
matrix = np.pad(np.zeros((3, 3)), pad_width=1,constant_values=1)

matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Expected output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 9. Add a border filled with 0's on the two sides of an array.

> Hint: [np.pad](https://numpy.org/doc/stable/reference/generated/numpy.pad.html)

In [ ]:
arr = np.array([1, 2, 3])
arr2 = np.pad(arr , pad_width=1 , constant_values=0)
arr2

array([0, 1, 2, 3, 0])

In [ ]:
# Expected output

array([0, 1, 2, 3, 0])

#### 10. Create an array of all the even integers from 10 to 50

In [ ]:
arr = np.arange(10 ,51, 2)

arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Expected output

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 11. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix = np.arange(0,9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Expected output

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 12. Create a 3x3 identity matrix

In [ ]:
matrix = np.identity(3)
matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Expected output

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 13. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

> Hint: [np.diag](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

In [ ]:
matrix = np.diag(np.array([1, 2, 3, 4]), k=-1)

matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# Expected output

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 14. Use NumPy to generate a random number between 0 and 1

**Note**: Your result's value should be different from the one shown below.

In [ ]:
np.array([np.random.rand()])

array([0.8320699])

In [ ]:
# Expected output

array([0.65248055])

#### 15. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

**Note**: Your result's values should be different from the ones shown below.

In [ ]:
np.random.normal(loc=0, scale=1, size=25)

array([-0.99590285,  0.78654188,  0.30610761,  1.35687424, -1.55924235,
        0.12544302,  0.74121617, -2.25579445, -1.17066984, -1.14302473,
        0.92480862,  0.72980462,  0.5901589 , -0.50136232, -0.92910474,
       -0.53978249, -0.08089598,  0.44865335, -0.364071  , -0.37355106,
        1.12859569, -0.58181582, -0.5518688 ,  0.71982022, -1.09149869])

In [ ]:
# Expected output

array([ 1.80076712, -1.12375847, -0.98524305,  0.11673573,  1.96346762,
        1.81378592, -0.33790771,  0.85012656,  0.0100703 , -0.91005957,
        0.29064366,  0.69906357,  0.1774377 , -0.61958694, -0.45498611,
       -2.0804685 , -0.06778549,  1.06403819,  0.4311884 , -1.09853837,
        1.11980469, -0.48751963,  1.32517611, -0.61775122, -0.00622865])

#### 16. Create a 3x3x3 array with random values drawn from the uniform distribution

**Note**: Your result's values should be different from the ones shown below.


In [ ]:
np.random.uniform(low=0, high=1, size=(3,3,3))

array([[[0.7351878 , 0.38164037, 0.73641896],
        [0.93477731, 0.56584545, 0.55698377],
        [0.42851442, 0.91751811, 0.1409255 ]],

       [[0.64475521, 0.94009622, 0.95589223],
        [0.69322103, 0.80436188, 0.92846562],
        [0.17154439, 0.27277097, 0.14746433]],

       [[0.14528762, 0.4020651 , 0.12512759],
        [0.16819579, 0.86741168, 0.43337008],
        [0.04775693, 0.3769702 , 0.81495174]]])

In [ ]:
# Expected output

array([[[0.93641099, 0.2920839 , 0.02292815],
        [0.00336922, 0.86947306, 0.68416644],
        [0.8901026 , 0.3837379 , 0.28653589]],

       [[0.10726099, 0.43744832, 0.00470833],
        [0.29069139, 0.64529908, 0.85020447],
        [0.51284435, 0.41215324, 0.19622211]],

       [[0.43004522, 0.92649706, 0.09472069],
        [0.76510854, 0.49565729, 0.56232861],
        [0.07813665, 0.49086324, 0.45172232]]])

#### 17. Create a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values.

**Note**: Your result's values should be different from the ones shown below.

In [ ]:
arr = np.random.uniform(low=0, high=1, size=(10,10))
print(arr)
print("Its min value: ", np.min(arr) )
print("Its max value: ", np.max(arr) )

[[0.86642452 0.10650925 0.1481534  0.04825958 0.94702515 0.77627815
  0.51655302 0.85201011 0.56661956 0.84683086]
 [0.33815153 0.01810346 0.7183076  0.71230689 0.88064721 0.99007922
  0.9788708  0.2904711  0.68834078 0.83364015]
 [0.21649797 0.13429995 0.42386524 0.33333682 0.14414147 0.04663162
  0.27708416 0.81145409 0.54367182 0.60182383]
 [0.0760427  0.65533118 0.49963691 0.10909692 0.88869644 0.83951765
  0.54688525 0.98674452 0.39443851 0.86113178]
 [0.00867531 0.74546673 0.95797549 0.94834243 0.27747543 0.95920025
  0.28848672 0.7358901  0.17320557 0.276199  ]
 [0.16264497 0.0527354  0.52259468 0.79120499 0.65156524 0.03914431
  0.8660367  0.38213903 0.00631433 0.73573367]
 [0.27423581 0.5455243  0.20496604 0.93814374 0.63202288 0.03944449
  0.105172   0.51246253 0.4464496  0.04545307]
 [0.44596739 0.0903533  0.42854622 0.24938862 0.04874741 0.10942718
  0.52890089 0.38288226 0.94527235 0.37429295]
 [0.24476302 0.27887479 0.30700945 0.42021274 0.8376549  0.10692976
  0.39984649

In [ ]:
# Expected output

The array: [[0.19932859 0.92905065 0.55492647 0.09878608 0.0421074  0.74219358
  0.92844055 0.62528946 0.35357668 0.88013918]
 [0.36971412 0.74932736 0.02445995 0.72873717 0.48864481 0.14421664
  0.56846658 0.40363749 0.3233466  0.95147426]
 [0.98339368 0.39612436 0.03609193 0.10611245 0.1410213  0.21099682
  0.3285783  0.39140252 0.88863881 0.81498748]
 [0.25423077 0.0756975  0.77587885 0.29315387 0.56795003 0.90145549
  0.95278316 0.63800115 0.14696466 0.08528442]
 [0.08048731 0.55554534 0.21157669 0.37491896 0.95567126 0.72478012
  0.64849367 0.05571253 0.12339177 0.95575902]
 [0.90842177 0.74316806 0.61710506 0.05885491 0.88051201 0.86814746
  0.26131788 0.89392307 0.45475956 0.26810516]
 [0.79185601 0.19973093 0.10674687 0.9080987  0.50335231 0.17405093
  0.39030326 0.48112173 0.74450033 0.76288692]
 [0.68992283 0.52305591 0.94364282 0.623963   0.04065964 0.23544532
  0.38685327 0.9687442  0.529897   0.37273771]
 [0.88262217 0.90518014 0.24570464 0.49601259 0.23893452 0.53227759
 

#### 18. Create a random array with values drawn from the uniform distribution of size 30 and find the mean value

In [ ]:
arr=np.random.uniform(low=0, high=1, size=30)
print("The array: ",arr)
print("Its mean: ",np.mean(arr))

The array:  [0.57950081 0.98159271 0.0576422  0.8396955  0.35619877 0.84262891
 0.40703076 0.54696731 0.47405279 0.09344741 0.34119112 0.45983178
 0.36689    0.07308466 0.85912369 0.82459965 0.31244608 0.06628955
 0.64083252 0.64555105 0.6367786  0.99817715 0.82551005 0.32157988
 0.18652012 0.67637219 0.5847315  0.83423587 0.28018244 0.79181245]
Its mean:  0.5301499175748282


In [ ]:
# Expected output

The array: [0.65580703 0.66012918 0.44607318 0.08230611 0.03965247 0.98197551
 0.07286258 0.08288793 0.5283879  0.26948948 0.29579988 0.44204416
 0.42570657 0.74707057 0.96866384 0.96437312 0.38116077 0.74621085
 0.26497925 0.33115365 0.963408   0.05087827 0.36557266 0.66121816
 0.24851936 0.25971588 0.40104167 0.90926914 0.80488701 0.31365462]
Its mean: 0.4788299599451823


#### 19. Create the following matrix:

In [ ]:
arr = np.arange(0.01,1.01,0.01).reshape((10,10))
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Expected output

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 20. Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr = np.linspace(0, 1, num=20)

arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# Expected output

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a starting matrix (be sure to run the cell below!), and be asked to replicate the resulting matrix outputs.

In all of the solutions until the last task before the section `NumPy Operations` you should be using `mat`.

In [ ]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 21. Write code that reproduces the output shown below.

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Expected output

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 22. Write code that reproduces the output shown below.

In [ ]:
mat[3][4]

20

In [ ]:
# Expected output

20

#### 23. Write code that reproduces the output shown below.

In [ ]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Expected output

array([[ 2],
       [ 7],
       [12]])

#### 24. Write code that reproduces the output shown below.

In [ ]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [ ]:
# Expected output

array([21, 22, 23, 24, 25])

#### 25. Write code that reproduces the output shown below.

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Expected output

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 26. Find the indices of the non-zero elements in the provided array.

In [ ]:
arr = np.array([1,2,0,0,4,0])

out = np.nonzero(arr)
out

(array([0, 1, 4]),)

In [ ]:
# Expected output

array([0, 1, 4])

## NumPy Operations

#### 27. Get the sum of all the values in mat

In [ ]:
np.sum(mat)

325

In [ ]:
# Expected output

325

#### 28. Get the standard deviation of the values in mat

In [ ]:
np.std(mat)

7.211102550927978

In [ ]:
# Expected output

7.211102550927978

#### 29. Get the sum of all the columns in mat

In [ ]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected output

array([55, 60, 65, 70, 75])

#### 30. Create and multiply a 5x3 matrix by a 3x2 matrix (matrix product). The matrices can hold random values or you can create them manually.

**Note**: In this example output the matrices held random values, so your result's values should be different from the ones shown below.

In [ ]:
mat1 = np.random.rand(5,3)
mat2 = np.random.rand(3,2)

np.dot(mat1,mat2)

array([[0.75238289, 1.45952533],
       [1.06446659, 1.9411312 ],
       [0.76482664, 1.46755744],
       [0.46892938, 0.8889802 ],
       [0.1634065 , 0.29589694]])

In [ ]:
# Expected output

array([[0.92284566, 0.4834381 ],
       [1.36591969, 0.86692985],
       [0.92732258, 0.57791729],
       [1.20870496, 0.66362074],
       [1.48551291, 0.86352205]])

#### 31. Create a 1D array of random integers between 0 and 9. Negate all elements which are between 3 and 8.

In [ ]:
arr = np.random.randint(0, 10, size=10)
for i in range(len(arr)):
  if (arr[i]>2 and arr[i]<9) : arr[i] *= -1

arr

array([-7, -7, -6,  2,  1, -6,  2,  1, -5, -7])

In [ ]:
# Expected output

array([ 4,  2,  5, -7, -2,  0, -3, -6, -8,  4])

#### 32. Create a random array of size 10 and sort it

In [ ]:
arr = np.random.uniform(0, 10, size=10)
np.sort(arr)

array([0.05981274, 0.40748779, 1.31435201, 4.25889388, 6.75859757,
       6.76245159, 7.52766355, 8.05342041, 8.55568617, 9.96221173])

In [ ]:
# Expected output

array([0.21557229, 0.29775351, 0.31513898, 0.48094387, 0.56395818,
       0.61094507, 0.65782361, 0.73666887, 0.74573749, 0.97557176])

#### 33. Create random vector of values drawn from the uniform distribution of size 10 and replace the maximum value by 0

In [ ]:
arr = np.random.uniform(0, 1, size=10)
print("The array: ",arr)
arr[np.argmax(arr)] = 0

print("Result: ",arr)

The array:  [0.88814421 0.45933088 0.8754658  0.10856191 0.87205874 0.29762764
 0.489414   0.38665176 0.04742558 0.42547833]
Result:  [0.         0.45933088 0.8754658  0.10856191 0.87205874 0.29762764
 0.489414   0.38665176 0.04742558 0.42547833]


In [ ]:
# Expected output

The array: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.89686752 0.1562022  0.76741728 0.62775096]
Result: [0.79753115 0.51085823 0.86710259 0.25025854 0.39803838 0.65002613
 0.         0.1562022  0.76741728 0.62775096]


#### 34. What function can we use to ensure that we always get the same random numbers?

> **Your answer**: ...np.random.seed()...